version: '2'
services:
    influxdb:
      image: influxdb:2.0
      volumes:
        - influxdb_data:/var/lib/influxdb2
        - influxdb_conf:/etc/influxdb2
      ports:
        - "8086:8086"
      environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: password
        DOCKER_INFLUXDB_INIT_ORG: sharemiale
        DOCKER_INFLUXDB_INIT_BUCKET: iot_bucket
        DOCKER_INFLUXDB_INIT_RETENTION: 1w
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
      container_name: influx-db
      
    node-red:
      image: nodered/node-red
      volumes:
        - nodered_data:/data
      ports:
        - "1880:1880"
      depends_on:
        - influxdb
      container_name: node-red
volumes:
    nodered_data: {}
    influxdb_data: {}
    influxdb_conf: {}
