version: '3'
services:
  
    node-red:
      image: nodered/node-red
      container_name: nodered
      volumes:
        - nodered_data:/data
      ports:
        - "1881:1880"
      networks:
        - net_bd

    namenode:
      image: owuor/hdfs-namenode
      container_name: namenode
      restart: always
      ports:
        - 9870:9870
        - 9000:9000
      volumes:
        - hadoop_namenode:/hadoop/dfs/name
      environment:
        - CLUSTER_NAME=test
      env_file:
        - ./configs/hadoop.env
      networks:
        - net_bd

    datanode:
      image: owuor/hdfs-datanode
      container_name: datanode
      restart: always
      ports:
        - 9864:9864
      volumes:
        - hadoop_datanode:/hadoop/dfs/data
      depends_on:
        - namenode
      environment:
        SERVICE_PRECONDITION: "namenode:9870"
      env_file:
        - ./configs/hadoop.env
      networks:
        - net_bd

    zeppelin:
      image: apache/zeppelin:0.9.0
      container_name: zeppelin
      volumes:
        - zeppelin_notebook:/opt/zeppelin/notebook
        - zeppelin_logs:/opt/zeppelin/logs
      ports:
        - "8082:8080"
      environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      networks:
        - net_bd

    streamsets:
      image: streamsets/datacollector:3.13.0-latest
      container_name: streamsets
      ports:
        - "18630:18630"
      networks:
        - net_bd

    zookeeper:
      image: bitnami/zookeeper:3.7.1
      container_name: zookeeper
      ports:
        - 2181:2181
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
      networks:
        - net_bd

    kafka:
      image: bitnami/kafka:3.4
      container_name: kafka
      ports:
        - 9092:9092
        - 9093:9093
      env_file:
        - ./configs/kafka.env
      depends_on:
        - zookeeper
      networks:
        - net_bd

volumes:
    nodered_data: {}
    zeppelin_logs: {}
    zeppelin_notebook: {}
    hadoop_datanode: {}
    hadoop_namenode: {}

networks:
  net_bd:
    name: net_bd
    driver: bridge
